version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      PORT: 2000
    ports:
      - "3001:2000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:jdiesel@postgres:5432/HACKDB
    ports:
      - "3000:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jdiesel
      POSTGRES_DB: HACKDB
    ports:
      - "5432:5432" # Expose PostgreSQL port
