# Use the Node.js image as the base image for the frontend
FROM node:latest as frontend

# Set the working directory to /app
WORKDIR /app/frontend

# Copy the frontend source code into the container
COPY ./check24-hackatum-client /app/frontend

# Install dependencies
RUN npm install

# Expose the port on which the Svelte app will run
EXPOSE 3000

# Start the Svelte development server
CMD npm run dev -- --host 0.0.0.0

