version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:jdiesel@postgres:5432/HACKDB
    ports:
      - "8080:8080" # Adjust the port as needed

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000" # Adjust the port as needed

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jdiesel
      POSTGRES_DB: HACKDB
    ports:
      - "5432:5432" # Expose PostgreSQL port
