version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:jdiesel@postgres:5432/HACKDB # Corrected database name
    ports:
      - "8080:8080" # Adjust the port as needed

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jdiesel
      POSTGRES_DB: HACKDB
    ports:
      - "5432:5432" # Expose PostgreSQL port
